name: utherm-release
channels:
  - conda-forge
  - pytorch
variables:
  PYTHONNOUSERSITE: "1"
dependencies:
  - python=3.11
  - numpy=1.26
  - scipy=1.17.1
  - pandas=3.0.5
  - matplotlib=3.11.1
  - gdal=3.11.5
  - rasterio=1.4.4
  - netcdf4=1.7.4=nompi_py311hc841c2f_109
  - xarray=2026.7.0
  - pytz
  - timezonefinder=6.5.9
  - tqdm
  - shapely=2
  - geopandas=1.1.1
  - pyproj=3.7.2
  - requests
  - pystac-client
  - planetary-computer
  - scikit-learn
  - cdsapi
  - libpdal-core=2.9.2
  - python-pdal=3.5.3=py311hf8204c7_0
  - pytorch=2.2.2=py3.11_cpu_0
  - pytest
  - pyqt
  - pip
